name: Smoke Test Run
on:
  deployment_status:

jobs:
  smoke-test:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    uses: mento-protocol/mento-automation-tests/.github/workflows/smoke-mento-web-test.yml@feat/AUT-1-view-pw-report-on-ci
    with:
      CUSTOM_URL: ${{ github.event.deployment_status.environment_url }}
      IS_MAINNET: 'false'
    secrets: inherit
